s = set()

set_e_1 = int(input("enter a number: "))
s.add(set_e_1)
set_e_2 = int(input("enter a number: "))
s.add(set_e_2)
set_e_3 = int(input("enter a number: "))
s.add(set_e_3)
set_e_4 = int(input("enter a number: "))
s.add(set_e_4)
set_e_5 = int(input("enter a number: "))
s.add(set_e_5)
set_e_6 = int(input("enter a number: "))
s.add(set_e_6)
set_e_7 = int(input("enter a number: "))
s.add(set_e_7)
set_e_8 = int(input("enter a number: "))
s.add(set_e_8)

print(s)
